import numpy
a=numpy.arange(6,dtype='i8')
print(a)
print(a.dtype)

b=numpy.arange(24).reshape(2,3,4)
print(b.ravel())
print(b)
print(b.flatten())
print(b)
a1=numpy.arange(9).reshape(3,3)
b1=a1*2
print(a1)
print(b1)
c1=numpy.hstack((a1,b1))
print(c1)
d1=numpy.concatenate((a1,b1),axis=1)
print(d1)
c2=numpy.vstack((a1,b1))
print(c2)
d2=numpy.concatenate((a1,b1),axis=0)
print(d2)
c3=numpy.dstack((a1,b1))
print(c3)
c4=numpy.column_stack((a1,b1))
print(c4)
print(c4==c1)
c5=numpy.row_stack((a1,b1))
print(c5==c2)

a2=numpy.arange(9).reshape(3,3)
e1=numpy.hsplit(a2,3)
print(e1)
e2=numpy.split(a2,3,axis=1)
print(e2)
e3=numpy.vsplit(a2,3)
print(e3)
e4=numpy.split(a2,3,axis=0)
print(e4)

f=numpy.arange(24).reshape(2,12)
print(f.ndim)
g=f.T
print(g)
f1=numpy.arange(4)
print(f1)
print(f1.ndim)
print(f1.T)

p=numpy.array([1.j+1,2.j+3])
print(p)
print(p.real)
q=p.tolist()
print(q)